/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiMarket_statusRouteImport } from './routes/api/market_status'
import { Route as ApiWatchlistSymbolRouteImport } from './routes/api/watchlist.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarket_statusRoute = ApiMarket_statusRouteImport.update({
  id: '/api/market_status',
  path: '/api/market_status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistSymbolRoute = ApiWatchlistSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => ApiWatchlistRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/market_status': typeof ApiMarket_statusRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/watchlist/$symbol': typeof ApiWatchlistSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/market_status': typeof ApiMarket_statusRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/watchlist/$symbol': typeof ApiWatchlistSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/market_status': typeof ApiMarket_statusRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/watchlist/$symbol': typeof ApiWatchlistSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/market_status'
    | '/api/prices'
    | '/api/quote'
    | '/api/watchlist'
    | '/api/watchlist/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/market_status'
    | '/api/prices'
    | '/api/quote'
    | '/api/watchlist'
    | '/api/watchlist/$symbol'
  id:
    | '__root__'
    | '/'
    | '/api/market_status'
    | '/api/prices'
    | '/api/quote'
    | '/api/watchlist'
    | '/api/watchlist/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMarket_statusRoute: typeof ApiMarket_statusRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market_status': {
      id: '/api/market_status'
      path: '/api/market_status'
      fullPath: '/api/market_status'
      preLoaderRoute: typeof ApiMarket_statusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/$symbol': {
      id: '/api/watchlist/$symbol'
      path: '/$symbol'
      fullPath: '/api/watchlist/$symbol'
      preLoaderRoute: typeof ApiWatchlistSymbolRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
  }
}

interface ApiWatchlistRouteChildren {
  ApiWatchlistSymbolRoute: typeof ApiWatchlistSymbolRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistSymbolRoute: ApiWatchlistSymbolRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMarket_statusRoute: ApiMarket_statusRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
